export const CLOUD_LIST_DATA = [
  {
    id: '1',
    provider: 'AWS',
    name: 'AWS OPS',
    proxyUrl: '',
    cloudGroupName: ['AWS-Group', 'default'],
    eventProcessEnabled: true,
    userActivityEnabled: false,
    scheduleScanEnabled: false,
    scheduleScanSetting: {
      frequency: 'DAY',
      hour: '0',
      minute: '0',
    },
    credentialType: 'ACCESS_KEY',
    credentials: {
      accessKey: 'AK********FF',
      secretAccessKey: 'N+********aZ',
    },
    regionList: [
      'global',
      'ap-northeast-1',
      'ap-northeast-2',
      'ap-northeast-3',
      'ap-south-1',
      'ap-southeast-1',
      'ap-southeast-2',
      'ca-central-1',
      'eu-central-1',
      'eu-north-1',
      'eu-west-1',
      'eu-west-2',
      'eu-west-3',
      'sa-east-1',
      'us-east-1',
      'us-east-2',
      'us-west-1',
      'us-west-2',
    ],
  },
  {
    id: '2',
    provider: 'AWS',
    name: 'AWS DEV',
    cloudGroupName: [],
    eventProcessEnabled: true,
    userActivityEnabled: false,
    scheduleScanEnabled: false,
    scheduleScanSetting: {
      frequency: 'HOUR',
      minute: '30',
    },
    credentialType: 'ACCESS_KEY',
    credentials: {
      accessKey: 'AK********FF',
      secretAccessKey: 'N+********aZ',
    },
    regionList: ['global'],
  },
  {
    id: '3',
    provider: 'AWS',
    name: 'AWS STAGE',
    cloudGroupName: ['default'],
    eventProcessEnabled: true,
    userActivityEnabled: false,
    scheduleScanEnabled: false,
    scheduleScanSetting: {
      frequency: 'MONTH',
      date: '15',
      hour: '3',
      minute: '20',
    },
    credentialType: 'ACCESS_KEY',
    credentials: {
      accessKey: 'AK********FF',
      secretAccessKey: 'N+********aZ',
    },
    regionList: ['global', 'ap-northeast-2'],
    eventSource: {
      cloudTrailName: 'test-trail',
    },
  },
  {
    id: '4',
    provider: 'AWS',
    name: 'AWS PROD',
    cloudGroupName: ['AWS-Group'],
    eventProcessEnabled: true,
    userActivityEnabled: false,
    scheduleScanEnabled: false,
    scheduleScanSetting: {
      frequency: 'WEEK',
      weekday: 'FRI',
      hour: '12',
      minute: '15',
    },
    credentialType: 'ACCESS_KEY',
    credentials: {
      accessKey: 'AK********FF',
      secretAccessKey: 'N+********aZ',
      roleArn: 'TestRole',
    },
    regionList: ['global', 'ap-northeast-1', 'ap-northeast-2', 'ap-northeast-3'],
    eventSource: {
      cloudTrailName: 'TestTrail',
    },
  },
];
